name: Links
on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types: [completed]
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose --no-progress
            'https://cmoineau.github.io/sitemap.xml'
          fail: true
